// Smart In-Memory Relational Database Engine faithfully simulating Oracle DB
// for offline testing, viva demonstrations, and automatic fallback.
import { initialSeedData } from './seedData.js';

class InMemoryOracleEngine {
  constructor() {
    this.tables = JSON.parse(JSON.stringify(initialSeedData));
    this.schemaMetadata = this.buildMetadata();
  }

  resetData() {
    this.tables = JSON.parse(JSON.stringify(initialSeedData));
  }

  buildMetadata() {
    return {
      USER_TABLES: Object.keys(initialSeedData).map(tName => ({
        TABLE_NAME: tName.toUpperCase(),
        TABLESPACE_NAME: 'USERS',
        STATUS: 'VALID',
        NUM_ROWS: initialSeedData[tName].length,
        LAST_ANALYZED: '2026-09-03 22:00:00'
      })),
      USER_TAB_COLUMNS: [
        // CANDIDATE
        { TABLE_NAME: 'CANDIDATE', COLUMN_NAME: 'CAND_ID', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 5, DATA_SCALE: 0, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'CANDIDATE', COLUMN_NAME: 'FNAME', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 30, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 2 },
        { TABLE_NAME: 'CANDIDATE', COLUMN_NAME: 'MNAME', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 30, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 3 },
        { TABLE_NAME: 'CANDIDATE', COLUMN_NAME: 'LNAME', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 30, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 4 },
        { TABLE_NAME: 'CANDIDATE', COLUMN_NAME: 'DOB', DATA_TYPE: 'DATE', DATA_LENGTH: 7, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 5 },
        { TABLE_NAME: 'CANDIDATE', COLUMN_NAME: 'GENDER', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 6 },
        { TABLE_NAME: 'CANDIDATE', COLUMN_NAME: 'REG_DATE', DATA_TYPE: 'DATE', DATA_LENGTH: 7, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 7 },
        { TABLE_NAME: 'CANDIDATE', COLUMN_NAME: 'EDU_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 8 },
        { TABLE_NAME: 'CANDIDATE', COLUMN_NAME: 'APP_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 9 },
        { TABLE_NAME: 'CANDIDATE', COLUMN_NAME: 'DEP_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 10 },
        { TABLE_NAME: 'CANDIDATE', COLUMN_NAME: 'INT_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 11 },

        // CANDIDATE_ADDRESS
        { TABLE_NAME: 'CANDIDATE_ADDRESS', COLUMN_NAME: 'CAND_ID', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 5, DATA_SCALE: 0, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'CANDIDATE_ADDRESS', COLUMN_NAME: 'HOUSE_NO', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 20, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'CANDIDATE_ADDRESS', COLUMN_NAME: 'CITY', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 40, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 3 },
        { TABLE_NAME: 'CANDIDATE_ADDRESS', COLUMN_NAME: 'STREET', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 60, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 4 },

        // CANDIDATE_EMAIL
        { TABLE_NAME: 'CANDIDATE_EMAIL', COLUMN_NAME: 'CAND_ID', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 5, DATA_SCALE: 0, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'CANDIDATE_EMAIL', COLUMN_NAME: 'EMAIL', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 100, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 2 },

        // CANDIDATE_PHONE
        { TABLE_NAME: 'CANDIDATE_PHONE', COLUMN_NAME: 'CAND_ID', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 5, DATA_SCALE: 0, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'CANDIDATE_PHONE', COLUMN_NAME: 'PHONE', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 15, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 2 },

        // JOB
        { TABLE_NAME: 'JOB', COLUMN_NAME: 'JOB_KEY', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 5, DATA_SCALE: 0, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'JOB', COLUMN_NAME: 'JOB_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'JOB', COLUMN_NAME: 'JOB_STATUS', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 20, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 3 },
        { TABLE_NAME: 'JOB', COLUMN_NAME: 'SALARY', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 10, DATA_SCALE: 2, NULLABLE: 'Y', COLUMN_ID: 4 },

        // JOB_DETAILS
        { TABLE_NAME: 'JOB_DETAILS', COLUMN_NAME: 'JOB_KEY', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 5, DATA_SCALE: 0, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'JOB_DETAILS', COLUMN_NAME: 'JOB_TITLE', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 60, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'JOB_DETAILS', COLUMN_NAME: 'DESCRIPTIVE', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 200, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 3 },
        { TABLE_NAME: 'JOB_DETAILS', COLUMN_NAME: 'APP_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 4 },

        // JOB_POSTING
        { TABLE_NAME: 'JOB_POSTING', COLUMN_NAME: 'JOB_TITLE', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 60, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'JOB_POSTING', COLUMN_NAME: 'CLOSING_DATE', DATA_TYPE: 'DATE', DATA_LENGTH: 7, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'JOB_POSTING', COLUMN_NAME: 'POSTED_DATE', DATA_TYPE: 'DATE', DATA_LENGTH: 7, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 3 },

        // APPLICATION
        { TABLE_NAME: 'APPLICATION', COLUMN_NAME: 'APP_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'APPLICATION', COLUMN_NAME: 'APP_STATUS', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 30, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'APPLICATION', COLUMN_NAME: 'FINAL_RESULT', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 30, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 3 },

        // APPLICATION_DATE
        { TABLE_NAME: 'APPLICATION_DATE', COLUMN_NAME: 'APP_DATE', DATA_TYPE: 'DATE', DATA_LENGTH: 7, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'APPLICATION_DATE', COLUMN_NAME: 'OFFER_LETTER', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 200, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'APPLICATION_DATE', COLUMN_NAME: 'FINAL_RESULT', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 30, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 3 },

        // APPLICATION_INFO
        { TABLE_NAME: 'APPLICATION_INFO', COLUMN_NAME: 'APP_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'APPLICATION_INFO', COLUMN_NAME: 'APP_DATE', DATA_TYPE: 'DATE', DATA_LENGTH: 7, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 2 },

        // EDUCATION
        { TABLE_NAME: 'EDUCATION', COLUMN_NAME: 'EDU_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'EDUCATION', COLUMN_NAME: 'CGPA', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 3, DATA_SCALE: 2, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'EDUCATION', COLUMN_NAME: 'SPECIALIZATION', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 60, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 3 },

        // EDUCATION_DEGREE
        { TABLE_NAME: 'EDUCATION_DEGREE', COLUMN_NAME: 'DEGREE', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 40, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'EDUCATION_DEGREE', COLUMN_NAME: 'UNIVERSITY', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 100, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'EDUCATION_DEGREE', COLUMN_NAME: 'START_YEAR', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 4, DATA_SCALE: 0, NULLABLE: 'Y', COLUMN_ID: 3 },

        // EDUCATION_END
        { TABLE_NAME: 'EDUCATION_END', COLUMN_NAME: 'EDU_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'EDUCATION_END', COLUMN_NAME: 'DEGREE', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 40, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'EDUCATION_END', COLUMN_NAME: 'END_YEAR', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 4, DATA_SCALE: 0, NULLABLE: 'Y', COLUMN_ID: 3 },

        // EXPERIENCE
        { TABLE_NAME: 'EXPERIENCE', COLUMN_NAME: 'EXP_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'EXPERIENCE', COLUMN_NAME: 'START_DATE', DATA_TYPE: 'DATE', DATA_LENGTH: 7, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'EXPERIENCE', COLUMN_NAME: 'JOB_TITLE', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 60, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 3 },

        // EXPERIENCE_CANDIDATE
        { TABLE_NAME: 'EXPERIENCE_CANDIDATE', COLUMN_NAME: 'EXP_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'EXPERIENCE_CANDIDATE', COLUMN_NAME: 'CAND_ID', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 5, DATA_SCALE: 0, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'EXPERIENCE_CANDIDATE', COLUMN_NAME: 'COMP_NAME', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 60, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 3 },
        { TABLE_NAME: 'EXPERIENCE_CANDIDATE', COLUMN_NAME: 'END_DATE', DATA_TYPE: 'DATE', DATA_LENGTH: 7, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 4 },

        // EXPERIENCE_COMPANY
        { TABLE_NAME: 'EXPERIENCE_COMPANY', COLUMN_NAME: 'COMP_NAME', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 60, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'EXPERIENCE_COMPANY', COLUMN_NAME: 'JOB_TITLE', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 60, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 2 },
        { TABLE_NAME: 'EXPERIENCE_COMPANY', COLUMN_NAME: 'END_DATE', DATA_TYPE: 'DATE', DATA_LENGTH: 7, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 3 },

        // LOCATION & STATE_CITY
        { TABLE_NAME: 'LOCATION', COLUMN_NAME: 'PINCODE', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 6, DATA_SCALE: 0, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'LOCATION', COLUMN_NAME: 'COUNTRY', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 40, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'LOCATION', COLUMN_NAME: 'STATE', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 40, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 3 },
        { TABLE_NAME: 'STATE_CITY', COLUMN_NAME: 'STATE', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 40, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'STATE_CITY', COLUMN_NAME: 'CITY', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 40, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 2 },

        // DEPENDENT
        { TABLE_NAME: 'DEPENDENT', COLUMN_NAME: 'DEP_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'DEPENDENT', COLUMN_NAME: 'DOB', DATA_TYPE: 'DATE', DATA_LENGTH: 7, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'DEPENDENT', COLUMN_NAME: 'RELATIONSHIP', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 30, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 3 },

        // INTERVIEW & INTERVIEW_DETAILS
        { TABLE_NAME: 'INTERVIEW', COLUMN_NAME: 'INT_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'INTERVIEW', COLUMN_NAME: 'INT_DATE', DATA_TYPE: 'DATE', DATA_LENGTH: 7, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'INTERVIEW', COLUMN_NAME: 'INT_TIME', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 3 },
        { TABLE_NAME: 'INTERVIEW_DETAILS', COLUMN_NAME: 'INT_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'INTERVIEW_DETAILS', COLUMN_NAME: 'INT_MODE', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 20, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'INTERVIEW_DETAILS', COLUMN_NAME: 'LOCATION', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 50, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 3 },
        { TABLE_NAME: 'INTERVIEW_DETAILS', COLUMN_NAME: 'INT_STATUS', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 20, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 4 },
        { TABLE_NAME: 'INTERVIEW_DETAILS', COLUMN_NAME: 'SCORE', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 5, DATA_SCALE: 2, NULLABLE: 'Y', COLUMN_ID: 5 },
        { TABLE_NAME: 'INTERVIEW_DETAILS', COLUMN_NAME: 'FEEDBACK', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 200, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 6 },

        // EMPLOYER & EMPLOYER_DETAILS & EMPLOYER_PHONE
        { TABLE_NAME: 'EMPLOYER', COLUMN_NAME: 'EMP_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'EMPLOYER', COLUMN_NAME: 'COMPANY_NAME', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 60, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'EMPLOYER', COLUMN_NAME: 'FOUNDED_YEAR', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 4, DATA_SCALE: 0, NULLABLE: 'Y', COLUMN_ID: 3 },
        { TABLE_NAME: 'EMPLOYER_DETAILS', COLUMN_NAME: 'EMP_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'EMPLOYER_DETAILS', COLUMN_NAME: 'COMPANY_MAIL', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 100, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'EMPLOYER_DETAILS', COLUMN_NAME: 'WEBSITE', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 100, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 3 },
        { TABLE_NAME: 'EMPLOYER_DETAILS', COLUMN_NAME: 'HEADQUARTER', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 60, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 4 },
        { TABLE_NAME: 'EMPLOYER_PHONE', COLUMN_NAME: 'EMP_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'EMPLOYER_PHONE', COLUMN_NAME: 'PHONE_NO', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 15, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 2 },

        // SKILL & SKILL_DETAILS
        { TABLE_NAME: 'SKILL', COLUMN_NAME: 'SKILL_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'SKILL', COLUMN_NAME: 'SKILL_NAME', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 50, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'SKILL_DETAILS', COLUMN_NAME: 'SKILL_NAME', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 50, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'SKILL_DETAILS', COLUMN_NAME: 'SKILL_CATEGORY', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 50, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'SKILL_DETAILS', COLUMN_NAME: 'DESCRIPTION', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 200, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 3 },

        // SUBTYPES
        { TABLE_NAME: 'FREELANCER', COLUMN_NAME: 'CAND_ID', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 5, DATA_SCALE: 0, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'FREELANCER', COLUMN_NAME: 'HOURLY_RATE', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 10, DATA_SCALE: 2, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'FREELANCER', COLUMN_NAME: 'PORTFOLIO_URL', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 150, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 3 },
        { TABLE_NAME: 'FRESHER', COLUMN_NAME: 'CAND_ID', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 5, DATA_SCALE: 0, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'FRESHER', COLUMN_NAME: 'GRAD_YEAR', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 4, DATA_SCALE: 0, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'FRESHER', COLUMN_NAME: 'INTERNSHIP_COUNT', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 3, DATA_SCALE: 0, NULLABLE: 'Y', COLUMN_ID: 3 },
        { TABLE_NAME: 'EXPERIENCED', COLUMN_NAME: 'CAND_ID', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 5, DATA_SCALE: 0, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'EXPERIENCED', COLUMN_NAME: 'TOTAL_EXP', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 4, DATA_SCALE: 1, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'EXPERIENCED', COLUMN_NAME: 'CURRENT_COMPANY', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 60, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 3 },

        // COMPANY & RECRUITMENT
        { TABLE_NAME: 'COMPANY', COLUMN_NAME: 'COMP_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'COMPANY', COLUMN_NAME: 'COMP_TYPE', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 40, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'COMPANY', COLUMN_NAME: 'EMP_COUNT', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 8, DATA_SCALE: 0, NULLABLE: 'Y', COLUMN_ID: 3 },
        { TABLE_NAME: 'COMPANY_EMPLOYER', COLUMN_NAME: 'COMP_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'COMPANY_EMPLOYER', COLUMN_NAME: 'EMP_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 2 },
        { TABLE_NAME: 'RECRUITMENT_AGENCY', COLUMN_NAME: 'AGENCY_NO', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'RECRUITMENT_AGENCY', COLUMN_NAME: 'AGENCY_NAME', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 80, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'RECRUITMENT_LICENSE', COLUMN_NAME: 'EMP_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'RECRUITMENT_LICENSE', COLUMN_NAME: 'LIC_NO', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 20, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'RECRUITMENT', COLUMN_NAME: 'EMP_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'RECRUITMENT', COLUMN_NAME: 'AGENCY_NO', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 2 },

        // RELATIONSHIPS
        { TABLE_NAME: 'REQUIRES', COLUMN_NAME: 'JOB_KEY', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 5, DATA_SCALE: 0, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'REQUIRES', COLUMN_NAME: 'SKILL_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 2 },
        { TABLE_NAME: 'REQUIRES', COLUMN_NAME: 'IS_MANDATORY', DATA_TYPE: 'CHAR', DATA_LENGTH: 1, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 3 },
        { TABLE_NAME: 'REQUIRES', COLUMN_NAME: 'MIN_YEARS', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 3, DATA_SCALE: 0, NULLABLE: 'Y', COLUMN_ID: 4 },

        { TABLE_NAME: 'MATCHED_TO', COLUMN_NAME: 'MATCH_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'MATCHED_TO', COLUMN_NAME: 'CAND_ID', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 5, DATA_SCALE: 0, NULLABLE: 'Y', COLUMN_ID: 2 },
        { TABLE_NAME: 'MATCHED_TO', COLUMN_NAME: 'JOB_KEY', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 5, DATA_SCALE: 0, NULLABLE: 'Y', COLUMN_ID: 3 },
        { TABLE_NAME: 'MATCHED_TO', COLUMN_NAME: 'MATCH_DATE', DATA_TYPE: 'DATE', DATA_LENGTH: 7, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 4 },

        { TABLE_NAME: 'APPLIES', COLUMN_NAME: 'CAND_ID', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 5, DATA_SCALE: 0, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'APPLIES', COLUMN_NAME: 'JOB_KEY', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 5, DATA_SCALE: 0, NULLABLE: 'N', COLUMN_ID: 2 },

        { TABLE_NAME: 'PREFERS', COLUMN_NAME: 'PINCODE', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 6, DATA_SCALE: 0, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'PREFERS', COLUMN_NAME: 'CAND_ID', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 5, DATA_SCALE: 0, NULLABLE: 'N', COLUMN_ID: 2 },

        { TABLE_NAME: 'REFERS', COLUMN_NAME: 'CAND_ID', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 5, DATA_SCALE: 0, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'REFERS', COLUMN_NAME: 'REFERRAL_DATE', DATA_TYPE: 'DATE', DATA_LENGTH: 7, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 2 },
        { TABLE_NAME: 'REFERS', COLUMN_NAME: 'REFERRAL_STATUS', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 20, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 3 },

        { TABLE_NAME: 'ASSESSED_FOR', COLUMN_NAME: 'CAND_ID', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 5, DATA_SCALE: 0, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'ASSESSED_FOR', COLUMN_NAME: 'JOB_KEY', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 5, DATA_SCALE: 0, NULLABLE: 'N', COLUMN_ID: 2 },
        { TABLE_NAME: 'ASSESSED_FOR', COLUMN_NAME: 'SKILL_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 3 },
        { TABLE_NAME: 'ASSESSED_FOR', COLUMN_NAME: 'MATCH_PER', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 5, DATA_SCALE: 2, NULLABLE: 'Y', COLUMN_ID: 4 },
        { TABLE_NAME: 'ASSESSED_FOR', COLUMN_NAME: 'ASS_DATE', DATA_TYPE: 'DATE', DATA_LENGTH: 7, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 5 },
        { TABLE_NAME: 'ASSESSED_FOR', COLUMN_NAME: 'ASS_SCORE', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 5, DATA_SCALE: 2, NULLABLE: 'Y', COLUMN_ID: 6 },

        { TABLE_NAME: 'HAS', COLUMN_NAME: 'CAND_ID', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 5, DATA_SCALE: 0, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'HAS', COLUMN_NAME: 'SKILL_ID', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 10, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 2 },
        { TABLE_NAME: 'HAS', COLUMN_NAME: 'PGD_LEVEL', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 30, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 3 },
        { TABLE_NAME: 'HAS', COLUMN_NAME: 'YEARS_OF_EXP', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 4, DATA_SCALE: 1, NULLABLE: 'Y', COLUMN_ID: 4 },

        // SECURITY
        { TABLE_NAME: 'APP_USERS', COLUMN_NAME: 'USER_ID', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 6, DATA_SCALE: 0, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'APP_USERS', COLUMN_NAME: 'USERNAME', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 50, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 2 },
        { TABLE_NAME: 'APP_USERS', COLUMN_NAME: 'FULL_NAME', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 100, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 3 },
        { TABLE_NAME: 'APP_USERS', COLUMN_NAME: 'EMAIL', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 100, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 4 },
        { TABLE_NAME: 'APP_USERS', COLUMN_NAME: 'ROLE', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 30, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 5 },
        { TABLE_NAME: 'APP_USERS', COLUMN_NAME: 'IS_ACTIVE', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 1, DATA_SCALE: 0, NULLABLE: 'N', COLUMN_ID: 6 },
        { TABLE_NAME: 'APP_USERS', COLUMN_NAME: 'CREATED_AT', DATA_TYPE: 'DATE', DATA_LENGTH: 7, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 7 },

        { TABLE_NAME: 'APP_AUDIT_LOG', COLUMN_NAME: 'LOG_ID', DATA_TYPE: 'NUMBER', DATA_LENGTH: 22, DATA_PRECISION: 10, DATA_SCALE: 0, NULLABLE: 'N', COLUMN_ID: 1 },
        { TABLE_NAME: 'APP_AUDIT_LOG', COLUMN_NAME: 'USERNAME', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 50, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 2 },
        { TABLE_NAME: 'APP_AUDIT_LOG', COLUMN_NAME: 'ROLE', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 30, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 3 },
        { TABLE_NAME: 'APP_AUDIT_LOG', COLUMN_NAME: 'ACTION', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 100, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 4 },
        { TABLE_NAME: 'APP_AUDIT_LOG', COLUMN_NAME: 'DETAILS', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 500, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 5 },
        { TABLE_NAME: 'APP_AUDIT_LOG', COLUMN_NAME: 'IP_ADDRESS', DATA_TYPE: 'VARCHAR2', DATA_LENGTH: 50, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'Y', COLUMN_ID: 6 },
        { TABLE_NAME: 'APP_AUDIT_LOG', COLUMN_NAME: 'CREATED_AT', DATA_TYPE: 'DATE', DATA_LENGTH: 7, DATA_PRECISION: null, DATA_SCALE: null, NULLABLE: 'N', COLUMN_ID: 7 }
      ],
      USER_CONSTRAINTS: [
        { CONSTRAINT_NAME: 'PK_CANDIDATE', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'CANDIDATE', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'PK_CANDIDATE_ADDRESS', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'CANDIDATE_ADDRESS', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'FK_CADDR_CANDIDATE', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'CANDIDATE_ADDRESS', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_CANDIDATE', DELETE_RULE: 'CASCADE' },
        { CONSTRAINT_NAME: 'PK_CANDIDATE_EMAIL', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'CANDIDATE_EMAIL', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'FK_CEMAIL_CANDIDATE', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'CANDIDATE_EMAIL', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_CANDIDATE', DELETE_RULE: 'CASCADE' },
        { CONSTRAINT_NAME: 'PK_CANDIDATE_PHONE', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'CANDIDATE_PHONE', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'FK_CPHONE_CANDIDATE', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'CANDIDATE_PHONE', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_CANDIDATE', DELETE_RULE: 'CASCADE' },
        
        { CONSTRAINT_NAME: 'PK_JOB', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'JOB', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'PK_JOB_DETAILS', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'JOB_DETAILS', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'FK_JOBDETAILS_JOB', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'JOB_DETAILS', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_JOB', DELETE_RULE: 'CASCADE' },
        { CONSTRAINT_NAME: 'PK_JOB_POSTING', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'JOB_POSTING', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },

        { CONSTRAINT_NAME: 'PK_EDUCATION', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'EDUCATION', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'PK_EDUCATION_DEGREE', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'EDUCATION_DEGREE', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'PK_EDUCATION_END', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'EDUCATION_END', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'FK_EDUEND_EDU', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'EDUCATION_END', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_EDUCATION', DELETE_RULE: 'CASCADE' },
        { CONSTRAINT_NAME: 'FK_EDUEND_DEGREE', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'EDUCATION_END', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_EDUCATION_DEGREE', DELETE_RULE: 'NO ACTION' },

        { CONSTRAINT_NAME: 'PK_APPLICATION', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'APPLICATION', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'PK_APPLICATION_DATE', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'APPLICATION_DATE', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'PK_APPLICATION_INFO', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'APPLICATION_INFO', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'FK_APPINFO_APPLICATION', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'APPLICATION_INFO', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_APPLICATION', DELETE_RULE: 'CASCADE' },
        { CONSTRAINT_NAME: 'FK_APPINFO_DATE', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'APPLICATION_INFO', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_APPLICATION_DATE', DELETE_RULE: 'NO ACTION' },

        { CONSTRAINT_NAME: 'PK_EXPERIENCE', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'EXPERIENCE', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'PK_EXP_CANDIDATE', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'EXPERIENCE_CANDIDATE', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'FK_EXPC_EXP', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'EXPERIENCE_CANDIDATE', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_EXPERIENCE', DELETE_RULE: 'CASCADE' },
        { CONSTRAINT_NAME: 'FK_EXPC_CANDIDATE', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'EXPERIENCE_CANDIDATE', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_CANDIDATE', DELETE_RULE: 'CASCADE' },
        { CONSTRAINT_NAME: 'PK_EXP_COMPANY', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'EXPERIENCE_COMPANY', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },

        { CONSTRAINT_NAME: 'PK_LOCATION', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'LOCATION', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'PK_STATE_CITY', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'STATE_CITY', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'PK_DEPENDENT', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'DEPENDENT', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },

        { CONSTRAINT_NAME: 'PK_INTERVIEW', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'INTERVIEW', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'PK_INTERVIEW_DETAILS', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'INTERVIEW_DETAILS', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'FK_INTDETAILS_INTERVIEW', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'INTERVIEW_DETAILS', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_INTERVIEW', DELETE_RULE: 'CASCADE' },

        { CONSTRAINT_NAME: 'PK_EMPLOYER', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'EMPLOYER', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'PK_EMPLOYER_DETAILS', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'EMPLOYER_DETAILS', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'FK_EMPDETAILS_EMPLOYER', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'EMPLOYER_DETAILS', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_EMPLOYER', DELETE_RULE: 'CASCADE' },
        { CONSTRAINT_NAME: 'PK_EMPLOYER_PHONE', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'EMPLOYER_PHONE', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'FK_EMPPHONE_EMPLOYER', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'EMPLOYER_PHONE', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_EMPLOYER', DELETE_RULE: 'CASCADE' },

        { CONSTRAINT_NAME: 'PK_SKILL', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'SKILL', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'PK_SKILL_DETAILS', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'SKILL_DETAILS', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },

        { CONSTRAINT_NAME: 'PK_FREELANCER', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'FREELANCER', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'FK_FREELANCER_CANDIDATE', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'FREELANCER', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_CANDIDATE', DELETE_RULE: 'CASCADE' },
        { CONSTRAINT_NAME: 'PK_FRESHER', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'FRESHER', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'FK_FRESHER_CANDIDATE', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'FRESHER', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_CANDIDATE', DELETE_RULE: 'CASCADE' },
        { CONSTRAINT_NAME: 'PK_EXPERIENCED', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'EXPERIENCED', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'FK_EXPERIENCED_CANDIDATE', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'EXPERIENCED', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_CANDIDATE', DELETE_RULE: 'CASCADE' },

        { CONSTRAINT_NAME: 'PK_COMPANY', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'COMPANY', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'PK_COMPANY_EMPLOYER', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'COMPANY_EMPLOYER', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'FK_COMPANY_EMP_COMP', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'COMPANY_EMPLOYER', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_COMPANY', DELETE_RULE: 'CASCADE' },
        { CONSTRAINT_NAME: 'FK_COMPANY_EMP_EMP', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'COMPANY_EMPLOYER', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_EMPLOYER', DELETE_RULE: 'CASCADE' },

        { CONSTRAINT_NAME: 'PK_RECRUITMENT_AGENCY', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'RECRUITMENT_AGENCY', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'PK_RECRUITMENT_LICENSE', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'RECRUITMENT_LICENSE', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'FK_RECRUIT_LICENSE_EMP', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'RECRUITMENT_LICENSE', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_EMPLOYER', DELETE_RULE: 'CASCADE' },
        { CONSTRAINT_NAME: 'PK_RECRUITMENT', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'RECRUITMENT', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'FK_RECRUIT_EMP', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'RECRUITMENT', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_EMPLOYER', DELETE_RULE: 'CASCADE' },
        { CONSTRAINT_NAME: 'FK_RECRUIT_AGENCY', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'RECRUITMENT', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_RECRUITMENT_AGENCY', DELETE_RULE: 'CASCADE' },

        { CONSTRAINT_NAME: 'PK_REQUIRES', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'REQUIRES', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'FK_REQUIRES_JOB', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'REQUIRES', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_JOB', DELETE_RULE: 'CASCADE' },
        { CONSTRAINT_NAME: 'FK_REQUIRES_SKILL', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'REQUIRES', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_SKILL', DELETE_RULE: 'CASCADE' },
        { CONSTRAINT_NAME: 'CK_REQUIRES_MANDATORY', CONSTRAINT_TYPE: 'C', TABLE_NAME: 'REQUIRES', SEARCH_CONDITION: 'is_mandatory IN (\'Y\',\'N\')', STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },

        { CONSTRAINT_NAME: 'PK_MATCHED_TO', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'MATCHED_TO', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'FK_MATCHED_CANDIDATE', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'MATCHED_TO', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_CANDIDATE', DELETE_RULE: 'CASCADE' },
        { CONSTRAINT_NAME: 'FK_MATCHED_JOB', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'MATCHED_TO', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_JOB', DELETE_RULE: 'CASCADE' },

        { CONSTRAINT_NAME: 'PK_APPLIES', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'APPLIES', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'FK_APPLIES_CANDIDATE', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'APPLIES', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_CANDIDATE', DELETE_RULE: 'CASCADE' },
        { CONSTRAINT_NAME: 'FK_APPLIES_JOB', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'APPLIES', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_JOB', DELETE_RULE: 'CASCADE' },

        { CONSTRAINT_NAME: 'PK_PREFERS', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'PREFERS', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'FK_PREFERS_LOCATION', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'PREFERS', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_LOCATION', DELETE_RULE: 'CASCADE' },
        { CONSTRAINT_NAME: 'FK_PREFERS_CANDIDATE', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'PREFERS', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_CANDIDATE', DELETE_RULE: 'CASCADE' },

        { CONSTRAINT_NAME: 'PK_REFERS', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'REFERS', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'FK_REFERS_CANDIDATE', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'REFERS', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_CANDIDATE', DELETE_RULE: 'CASCADE' },

        { CONSTRAINT_NAME: 'PK_ASSESSED_FOR', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'ASSESSED_FOR', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'FK_ASSESS_CANDIDATE', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'ASSESSED_FOR', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_CANDIDATE', DELETE_RULE: 'CASCADE' },
        { CONSTRAINT_NAME: 'FK_ASSESS_JOB', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'ASSESSED_FOR', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_JOB', DELETE_RULE: 'CASCADE' },
        { CONSTRAINT_NAME: 'FK_ASSESS_SKILL', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'ASSESSED_FOR', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_SKILL', DELETE_RULE: 'CASCADE' },
        { CONSTRAINT_NAME: 'CK_ASSESS_MATCH', CONSTRAINT_TYPE: 'C', TABLE_NAME: 'ASSESSED_FOR', SEARCH_CONDITION: 'match_per BETWEEN 0 AND 100', STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'CK_ASSESS_SCORE', CONSTRAINT_TYPE: 'C', TABLE_NAME: 'ASSESSED_FOR', SEARCH_CONDITION: 'ass_score BETWEEN 0 AND 100', STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },

        { CONSTRAINT_NAME: 'PK_HAS', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'HAS', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'FK_HAS_CANDIDATE', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'HAS', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_CANDIDATE', DELETE_RULE: 'CASCADE' },
        { CONSTRAINT_NAME: 'FK_HAS_SKILL', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'HAS', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_SKILL', DELETE_RULE: 'CASCADE' },

        { CONSTRAINT_NAME: 'FK_CANDIDATE_EDU', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'CANDIDATE', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_EDUCATION', DELETE_RULE: 'SET NULL' },
        { CONSTRAINT_NAME: 'FK_CANDIDATE_APP', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'CANDIDATE', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_APPLICATION', DELETE_RULE: 'SET NULL' },
        { CONSTRAINT_NAME: 'FK_CANDIDATE_DEP', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'CANDIDATE', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_DEPENDENT', DELETE_RULE: 'SET NULL' },
        { CONSTRAINT_NAME: 'FK_CANDIDATE_INT', CONSTRAINT_TYPE: 'R', TABLE_NAME: 'CANDIDATE', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: 'PK_INTERVIEW', DELETE_RULE: 'SET NULL' },

        { CONSTRAINT_NAME: 'PK_APP_USERS', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'APP_USERS', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'UQ_APP_USERS_USERNAME', CONSTRAINT_TYPE: 'U', TABLE_NAME: 'APP_USERS', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'CK_APP_USERS_ROLE', CONSTRAINT_TYPE: 'C', TABLE_NAME: 'APP_USERS', SEARCH_CONDITION: 'role IN (\'USER\', \'DATABASE_DESIGNER\', \'DBA\')', STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null },
        { CONSTRAINT_NAME: 'PK_APP_AUDIT_LOG', CONSTRAINT_TYPE: 'P', TABLE_NAME: 'APP_AUDIT_LOG', SEARCH_CONDITION: null, STATUS: 'ENABLED', R_CONSTRAINT_NAME: null, DELETE_RULE: null }
      ],
      USER_CONS_COLUMNS: [
        { CONSTRAINT_NAME: 'PK_CANDIDATE', TABLE_NAME: 'CANDIDATE', COLUMN_NAME: 'CAND_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_CANDIDATE_ADDRESS', TABLE_NAME: 'CANDIDATE_ADDRESS', COLUMN_NAME: 'CAND_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_CANDIDATE_EMAIL', TABLE_NAME: 'CANDIDATE_EMAIL', COLUMN_NAME: 'CAND_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_CANDIDATE_EMAIL', TABLE_NAME: 'CANDIDATE_EMAIL', COLUMN_NAME: 'EMAIL', POSITION: 2 },
        { CONSTRAINT_NAME: 'PK_CANDIDATE_PHONE', TABLE_NAME: 'CANDIDATE_PHONE', COLUMN_NAME: 'CAND_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_CANDIDATE_PHONE', TABLE_NAME: 'CANDIDATE_PHONE', COLUMN_NAME: 'PHONE', POSITION: 2 },
        { CONSTRAINT_NAME: 'PK_JOB', TABLE_NAME: 'JOB', COLUMN_NAME: 'JOB_KEY', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_JOB_DETAILS', TABLE_NAME: 'JOB_DETAILS', COLUMN_NAME: 'JOB_KEY', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_JOB_POSTING', TABLE_NAME: 'JOB_POSTING', COLUMN_NAME: 'JOB_TITLE', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_EDUCATION', TABLE_NAME: 'EDUCATION', COLUMN_NAME: 'EDU_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_EDUCATION_DEGREE', TABLE_NAME: 'EDUCATION_DEGREE', COLUMN_NAME: 'DEGREE', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_EDUCATION_END', TABLE_NAME: 'EDUCATION_END', COLUMN_NAME: 'EDU_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_APPLICATION', TABLE_NAME: 'APPLICATION', COLUMN_NAME: 'APP_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_APPLICATION_DATE', TABLE_NAME: 'APPLICATION_DATE', COLUMN_NAME: 'APP_DATE', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_APPLICATION_INFO', TABLE_NAME: 'APPLICATION_INFO', COLUMN_NAME: 'APP_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_EXPERIENCE', TABLE_NAME: 'EXPERIENCE', COLUMN_NAME: 'EXP_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_EXP_CANDIDATE', TABLE_NAME: 'EXPERIENCE_CANDIDATE', COLUMN_NAME: 'EXP_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_EXP_COMPANY', TABLE_NAME: 'EXPERIENCE_COMPANY', COLUMN_NAME: 'COMP_NAME', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_EXP_COMPANY', TABLE_NAME: 'EXPERIENCE_COMPANY', COLUMN_NAME: 'JOB_TITLE', POSITION: 2 },
        { CONSTRAINT_NAME: 'PK_EXP_COMPANY', TABLE_NAME: 'EXPERIENCE_COMPANY', COLUMN_NAME: 'END_DATE', POSITION: 3 },
        { CONSTRAINT_NAME: 'PK_LOCATION', TABLE_NAME: 'LOCATION', COLUMN_NAME: 'PINCODE', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_STATE_CITY', TABLE_NAME: 'STATE_CITY', COLUMN_NAME: 'STATE', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_DEPENDENT', TABLE_NAME: 'DEPENDENT', COLUMN_NAME: 'DEP_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_INTERVIEW', TABLE_NAME: 'INTERVIEW', COLUMN_NAME: 'INT_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_INTERVIEW_DETAILS', TABLE_NAME: 'INTERVIEW_DETAILS', COLUMN_NAME: 'INT_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_EMPLOYER', TABLE_NAME: 'EMPLOYER', COLUMN_NAME: 'EMP_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_EMPLOYER_DETAILS', TABLE_NAME: 'EMPLOYER_DETAILS', COLUMN_NAME: 'EMP_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_EMPLOYER_PHONE', TABLE_NAME: 'EMPLOYER_PHONE', COLUMN_NAME: 'EMP_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_EMPLOYER_PHONE', TABLE_NAME: 'EMPLOYER_PHONE', COLUMN_NAME: 'PHONE_NO', POSITION: 2 },
        { CONSTRAINT_NAME: 'PK_SKILL', TABLE_NAME: 'SKILL', COLUMN_NAME: 'SKILL_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_SKILL_DETAILS', TABLE_NAME: 'SKILL_DETAILS', COLUMN_NAME: 'SKILL_NAME', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_FREELANCER', TABLE_NAME: 'FREELANCER', COLUMN_NAME: 'CAND_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_FRESHER', TABLE_NAME: 'FRESHER', COLUMN_NAME: 'CAND_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_EXPERIENCED', TABLE_NAME: 'EXPERIENCED', COLUMN_NAME: 'CAND_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_COMPANY', TABLE_NAME: 'COMPANY', COLUMN_NAME: 'COMP_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_COMPANY_EMPLOYER', TABLE_NAME: 'COMPANY_EMPLOYER', COLUMN_NAME: 'COMP_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_COMPANY_EMPLOYER', TABLE_NAME: 'COMPANY_EMPLOYER', COLUMN_NAME: 'EMP_ID', POSITION: 2 },
        { CONSTRAINT_NAME: 'PK_RECRUITMENT_AGENCY', TABLE_NAME: 'RECRUITMENT_AGENCY', COLUMN_NAME: 'AGENCY_NO', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_RECRUITMENT_LICENSE', TABLE_NAME: 'RECRUITMENT_LICENSE', COLUMN_NAME: 'EMP_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_RECRUITMENT', TABLE_NAME: 'RECRUITMENT', COLUMN_NAME: 'EMP_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_RECRUITMENT', TABLE_NAME: 'RECRUITMENT', COLUMN_NAME: 'AGENCY_NO', POSITION: 2 },
        { CONSTRAINT_NAME: 'PK_REQUIRES', TABLE_NAME: 'REQUIRES', COLUMN_NAME: 'JOB_KEY', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_REQUIRES', TABLE_NAME: 'REQUIRES', COLUMN_NAME: 'SKILL_ID', POSITION: 2 },
        { CONSTRAINT_NAME: 'PK_MATCHED_TO', TABLE_NAME: 'MATCHED_TO', COLUMN_NAME: 'MATCH_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_APPLIES', TABLE_NAME: 'APPLIES', COLUMN_NAME: 'CAND_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_APPLIES', TABLE_NAME: 'APPLIES', COLUMN_NAME: 'JOB_KEY', POSITION: 2 },
        { CONSTRAINT_NAME: 'PK_PREFERS', TABLE_NAME: 'PREFERS', COLUMN_NAME: 'PINCODE', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_PREFERS', TABLE_NAME: 'PREFERS', COLUMN_NAME: 'CAND_ID', POSITION: 2 },
        { CONSTRAINT_NAME: 'PK_REFERS', TABLE_NAME: 'REFERS', COLUMN_NAME: 'CAND_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_REFERS', TABLE_NAME: 'REFERS', COLUMN_NAME: 'REFERRAL_DATE', POSITION: 2 },
        { CONSTRAINT_NAME: 'PK_ASSESSED_FOR', TABLE_NAME: 'ASSESSED_FOR', COLUMN_NAME: 'CAND_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_ASSESSED_FOR', TABLE_NAME: 'ASSESSED_FOR', COLUMN_NAME: 'JOB_KEY', POSITION: 2 },
        { CONSTRAINT_NAME: 'PK_ASSESSED_FOR', TABLE_NAME: 'ASSESSED_FOR', COLUMN_NAME: 'SKILL_ID', POSITION: 3 },
        { CONSTRAINT_NAME: 'PK_HAS', TABLE_NAME: 'HAS', COLUMN_NAME: 'CAND_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_HAS', TABLE_NAME: 'HAS', COLUMN_NAME: 'SKILL_ID', POSITION: 2 },
        { CONSTRAINT_NAME: 'PK_APP_USERS', TABLE_NAME: 'APP_USERS', COLUMN_NAME: 'USER_ID', POSITION: 1 },
        { CONSTRAINT_NAME: 'PK_APP_AUDIT_LOG', TABLE_NAME: 'APP_AUDIT_LOG', COLUMN_NAME: 'LOG_ID', POSITION: 1 }
      ],
      USER_INDEXES: [
        { INDEX_NAME: 'PK_CANDIDATE', TABLE_NAME: 'CANDIDATE', UNIQUENESS: 'UNIQUE', STATUS: 'VALID', TABLESPACE_NAME: 'USERS' },
        { INDEX_NAME: 'PK_JOB', TABLE_NAME: 'JOB', UNIQUENESS: 'UNIQUE', STATUS: 'VALID', TABLESPACE_NAME: 'USERS' },
        { INDEX_NAME: 'PK_APPLICATION', TABLE_NAME: 'APPLICATION', UNIQUENESS: 'UNIQUE', STATUS: 'VALID', TABLESPACE_NAME: 'USERS' },
        { INDEX_NAME: 'PK_EDUCATION', TABLE_NAME: 'EDUCATION', UNIQUENESS: 'UNIQUE', STATUS: 'VALID', TABLESPACE_NAME: 'USERS' },
        { INDEX_NAME: 'PK_EXPERIENCE', TABLE_NAME: 'EXPERIENCE', UNIQUENESS: 'UNIQUE', STATUS: 'VALID', TABLESPACE_NAME: 'USERS' },
        { INDEX_NAME: 'PK_EMPLOYER', TABLE_NAME: 'EMPLOYER', UNIQUENESS: 'UNIQUE', STATUS: 'VALID', TABLESPACE_NAME: 'USERS' },
        { INDEX_NAME: 'PK_SKILL', TABLE_NAME: 'SKILL', UNIQUENESS: 'UNIQUE', STATUS: 'VALID', TABLESPACE_NAME: 'USERS' },
        { INDEX_NAME: 'PK_INTERVIEW', TABLE_NAME: 'INTERVIEW', UNIQUENESS: 'UNIQUE', STATUS: 'VALID', TABLESPACE_NAME: 'USERS' },
        { INDEX_NAME: 'PK_LOCATION', TABLE_NAME: 'LOCATION', UNIQUENESS: 'UNIQUE', STATUS: 'VALID', TABLESPACE_NAME: 'USERS' },
        { INDEX_NAME: 'PK_DEPENDENT', TABLE_NAME: 'DEPENDENT', UNIQUENESS: 'UNIQUE', STATUS: 'VALID', TABLESPACE_NAME: 'USERS' },
        { INDEX_NAME: 'PK_APP_USERS', TABLE_NAME: 'APP_USERS', UNIQUENESS: 'UNIQUE', STATUS: 'VALID', TABLESPACE_NAME: 'USERS' }
      ],
      USER_OBJECTS: Object.keys(initialSeedData).map((tName, idx) => ({
        OBJECT_NAME: tName.toUpperCase(),
        OBJECT_TYPE: 'TABLE',
        STATUS: 'VALID',
        CREATED: '2026-09-03 22:00:00',
        LAST_DDL_TIME: '2026-09-03 22:00:00'
      })).concat([
        { OBJECT_NAME: 'SEQ_APP_USERS', OBJECT_TYPE: 'SEQUENCE', STATUS: 'VALID', CREATED: '2026-09-03 22:00:00', LAST_DDL_TIME: '2026-09-03 22:00:00' },
        { OBJECT_NAME: 'SEQ_APP_AUDIT_LOG', OBJECT_TYPE: 'SEQUENCE', STATUS: 'VALID', CREATED: '2026-09-03 22:00:00', LAST_DDL_TIME: '2026-09-03 22:00:00' },
        { OBJECT_NAME: 'TRG_APP_USERS_ID', OBJECT_TYPE: 'TRIGGER', STATUS: 'VALID', CREATED: '2026-09-03 22:00:00', LAST_DDL_TIME: '2026-09-03 22:00:00' },
        { OBJECT_NAME: 'TRG_APP_AUDIT_LOG_ID', OBJECT_TYPE: 'TRIGGER', STATUS: 'VALID', CREATED: '2026-09-03 22:00:00', LAST_DDL_TIME: '2026-09-03 22:00:00' }
      ])
    };
  }
}

export const inMemoryDb = new InMemoryOracleEngine();
